<?php
$complitedOrders = $this->getAllTheOrdersWithStateComplited();
$notComplitedOrders = $this->getAllTheOrdersWithStateDiferentThamComplited();
$activeProducts = $this->getActiveProducts();
?>

<table>
    <thead>
        <th><?php echo Mage::helper('softuni_statistics')->__('Completed Orders') ?></th>
        <th><?php echo Mage::helper('softuni_statistics')->__('Not Completed Orders') ?></th>
        <th><?php echo Mage::helper('softuni_statistics')->__('Active Products') ?></th>
    </thead>
    <tbody>
    <tr>
        <td><?php echo $complitedOrders?></td>
        <td><?php echo $notComplitedOrders?></td>
        <td><?php echo $activeProducts?></td>
    </tr>
    </tbody>
</table>